# Site settings
title: Popculturemecha
email: popculturemecha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome blog. Move along.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: popculturemecha
github_username:  popculturemecha

# Build settings
markdown: kramdown

permalink: /:categories/:title/

include: ['_pages']

excerpt_separator: '<!-- more -->'

slogan: "A Flexible Theme for Jekyll"



author: phlow


improve_content: https://github.com/Phlow/feeling-responsive/edit/gh-pages


urlimg: 'https://phlow.github.io/feeling-responsive/images/'


# Logo size is 600x80 pixels
logo: "logo.png"



language: "en"




defaults:
  -
    scope:
      path: "" 				# an empty string here means all files in the project
      type: "pages"
    values:
      show_meta: false 	# Hide metadata for all pages
      # sidebar:    		# Possible values › left, right › by default there will be no sidebar
      comments: false
      author: phlow     # Default author for pages
  -
    scope:
      path: ""
      type: "posts"
    values:
      show_meta: true   # Show metadata for all posts
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: phlow     # Default author for posts





# favicon-32x32:                          "favicon-32x32.png"
# touch-icon-192x192:                     "touch-icon-192x192.png"
# apple-touch-icon-180x180-precomposed:   "apple-touch-icon-180x180-precomposed.png"
# apple-touch-icon-152x152-precomposed:   "apple-touch-icon-152x152-precomposed.png"
# apple-touch-icon-144x144-precomposed:   "apple-touch-icon-144x144-precomposed.png"
# apple-touch-icon-120x120-precomposed:   "apple-touch-icon-120x120-precomposed.png"
# apple-touch-icon-114x114-precomposed:   "apple-touch-icon-114x114-precomposed.png"
# apple-touch-icon-76x76-precomposed:     "apple-touch-icon-76x76-precomposed.png"
# apple-touch-icon-72x72-precomposed:     "apple-touch-icon-72x72-precomposed.png"
# apple-touch-icon-precomposed:           "apple-touch-icon-precomposed.png"
# msapplication_tileimage:                "msapplication_tileimage.png"               # Size 144x144
# msapplication_tilecolor:                "#fabb00"